name: CI

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3

  tests:
    needs: pre-commit
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: Gr1N/setup-poetry@v8
      with:
        poetry-version: 1.4.1

    - name: install tox
      run: |
        pip3 install tox==3.24.4
        pip3 install tox-gh-actions==2.8.1

    - name: test with tox
      run: |
        tox
